version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    profiles: ["integration"]
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - "api"
  api: 
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    profiles: ["integration"]
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb?schema=public
      - APP_URL=http://localhost:3000
      - DISCORD_ID=${DISCORD_ID}
      - DISCORD_SECRET=${DISCORD_SECRET}
    ports:
      - "3010:3010"
      - "4000:4000"
    depends_on:
      - "db"
  db:
    image: postgres:14.1-alpine
    restart: always
    profiles: ["dev", "integration"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  db-test:
    image: postgres:14.1-alpine
    restart: always
    profiles: ["dev"]
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
volumes:
  db:
    driver: local
