name: 15-minute-cron
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request DELETE \
          --url 'https://yggdrasil.darthgeek.app/api/chat/message/purge' \
          --header 'Authorization: Bearer ${{ secrets.PROD_MAINTBOT_API_KEY }}'